"""Trip, Day, Activity, and Alert models."""
from sqlalchemy import Column, Integer, String, DateTime, Float, ForeignKey, JSON, Enum as SQLEnum
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import enum
from ..database import Base


class TripStatus(str, enum.Enum):
    """Trip status enum."""
    PLANNING = "planning"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class ActivityCategory(str, enum.Enum):
    """Activity category enum."""
    FOOD = "food"
    MUSEUM = "museum"
    SIGHTSEEING = "sightseeing"
    SHOPPING = "shopping"
    NIGHTLIFE = "nightlife"
    OUTDOOR = "outdoor"
    CULTURAL = "cultural"
    RELAXATION = "relaxation"
    TRANSPORT = "transport"
    ACCOMMODATION = "accommodation"
    OTHER = "other"


class ActivityStatus(str, enum.Enum):
    """Activity status enum."""
    PLANNED = "planned"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    SKIPPED = "skipped"


class AlertType(str, enum.Enum):
    """Alert type enum."""
    WEATHER = "weather"
    CLOSURE = "closure"
    SAFETY = "safety"
    TRANSIT = "transit"
    EVENT = "event"
    GENERAL = "general"


class AlertSeverity(str, enum.Enum):
    """Alert severity enum."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class Trip(Base):
    """Trip model."""

    __tablename__ = "trips"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    destination = Column(String, nullable=False)
    start_date = Column(DateTime(timezone=True), nullable=False)
    end_date = Column(DateTime(timezone=True), nullable=False)
    status = Column(SQLEnum(TripStatus), default=TripStatus.PLANNING)
    total_budget = Column(Float, nullable=True)

    # Additional metadata
    # Structure: {
    #   "destination_country": "France",
    #   "destination_city": "Paris",
    #   "coordinates": {"lat": 48.8566, "lng": 2.3522},
    #   "timezone": "Europe/Paris"
    # }
    metadata = Column(JSON, nullable=True, default={})

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="trips")
    days = relationship("Day", back_populates="trip", cascade="all, delete-orphan", order_by="Day.index")
    alerts = relationship("Alert", back_populates="trip", cascade="all, delete-orphan")
    messages = relationship("Message", back_populates="trip", cascade="all, delete-orphan")


class Day(Base):
    """Day model."""

    __tablename__ = "days"

    id = Column(Integer, primary_key=True, index=True)
    trip_id = Column(Integer, ForeignKey("trips.id"), nullable=False)
    date = Column(DateTime(timezone=True), nullable=False)
    index = Column(Integer, nullable=False)  # Day number (1, 2, 3...)
    notes = Column(String, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    trip = relationship("Trip", back_populates="days")
    activities = relationship("Activity", back_populates="day", cascade="all, delete-orphan", order_by="Activity.start_time")


class Activity(Base):
    """Activity model."""

    __tablename__ = "activities"

    id = Column(Integer, primary_key=True, index=True)
    day_id = Column(Integer, ForeignKey("days.id"), nullable=False)

    title = Column(String, nullable=False)
    description = Column(String, nullable=True)
    category = Column(SQLEnum(ActivityCategory), nullable=False)

    start_time = Column(DateTime(timezone=True), nullable=False)
    end_time = Column(DateTime(timezone=True), nullable=False)

    # Location information
    location = Column(String, nullable=True)  # Address or place name
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)

    cost_estimate = Column(Float, nullable=True)
    booking_url = Column(String, nullable=True)

    # Source: ai (generated by LLM) or user (manually added/modified)
    source = Column(String, default="ai")
    status = Column(SQLEnum(ActivityStatus), default=ActivityStatus.PLANNED)

    # Additional metadata
    # Structure: {
    #   "rating": 4.5,
    #   "reviews_count": 1234,
    #   "opening_hours": {...},
    #   "contact": {...},
    #   "tips": [...]
    # }
    metadata = Column(JSON, nullable=True, default={})

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    day = relationship("Day", back_populates="activities")


class Alert(Base):
    """Alert model."""

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    trip_id = Column(Integer, ForeignKey("trips.id"), nullable=False)
    activity_id = Column(Integer, ForeignKey("activities.id"), nullable=True)  # Optional link to specific activity

    type = Column(SQLEnum(AlertType), nullable=False)
    severity = Column(SQLEnum(AlertSeverity), default=AlertSeverity.INFO)

    message = Column(String, nullable=False)

    # Alternative suggestions (JSON array of activity options)
    # Structure: [
    #   {"title": "...", "description": "...", "location": "...", ...},
    #   ...
    # ]
    alternatives = Column(JSON, nullable=True, default=[])

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    resolved_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    trip = relationship("Trip", back_populates="alerts")
