import { Trip, ChatMessage, SafetyInfo, User, UserPreferences } from '../types';
import { mockUser, mockPreferences, mockTrips, mockChatMessages, mockSafetyInfo } from './mockData';

// Simulate network delay
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

// API Client class
class APIClient {
  private baseURL = 'https://api.example.com'; // Placeholder URL

  // User APIs
  async getCurrentUser(): Promise<User> {
    await delay(500);
    return mockUser;
  }

  async getUserPreferences(): Promise<UserPreferences> {
    await delay(300);
    return mockPreferences;
  }

  async updateUserPreferences(preferences: Partial<UserPreferences>): Promise<UserPreferences> {
    await delay(500);
    return { ...mockPreferences, ...preferences };
  }

  // Trip APIs
  async getTrips(): Promise<Trip[]> {
    await delay(800);
    return mockTrips;
  }

  async getTripById(tripId: string): Promise<Trip | null> {
    await delay(500);
    const trip = mockTrips.find(t => t.id === tripId);
    return trip || null;
  }

  async createTrip(trip: Omit<Trip, 'id' | 'createdAt' | 'updatedAt'>): Promise<Trip> {
    await delay(700);
    const newTrip: Trip = {
      ...trip,
      id: String(mockTrips.length + 1),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    mockTrips.push(newTrip);
    return newTrip;
  }

  async updateTrip(tripId: string, updates: Partial<Trip>): Promise<Trip | null> {
    await delay(600);
    const tripIndex = mockTrips.findIndex(t => t.id === tripId);
    if (tripIndex === -1) return null;

    const updatedTrip = {
      ...mockTrips[tripIndex],
      ...updates,
      updatedAt: new Date().toISOString(),
    };
    mockTrips[tripIndex] = updatedTrip;
    return updatedTrip;
  }

  async deleteTrip(tripId: string): Promise<boolean> {
    await delay(500);
    const tripIndex = mockTrips.findIndex(t => t.id === tripId);
    if (tripIndex === -1) return false;

    mockTrips.splice(tripIndex, 1);
    return true;
  }

  // Chat APIs
  async getChatMessages(tripId?: string): Promise<ChatMessage[]> {
    await delay(500);
    if (tripId) {
      return mockChatMessages.filter(m => m.tripId === tripId);
    }
    return mockChatMessages;
  }

  async postChatMessage(
    content: string,
    tripId?: string
  ): Promise<{ userMessage: ChatMessage; aiResponse: ChatMessage }> {
    await delay(1000);

    const userMessage: ChatMessage = {
      id: String(Date.now()),
      tripId,
      role: 'user',
      content,
      timestamp: new Date().toISOString(),
    };

    // Simulate AI response
    const aiResponse: ChatMessage = {
      id: String(Date.now() + 1),
      tripId,
      role: 'assistant',
      content: `This is a simulated AI response to: "${content}". In a real app, this would be generated by an AI service.`,
      timestamp: new Date().toISOString(),
    };

    mockChatMessages.push(userMessage, aiResponse);

    return { userMessage, aiResponse };
  }

  // Safety APIs
  async getSafetyInfo(country: string): Promise<SafetyInfo> {
    await delay(600);
    // In a real app, this would fetch country-specific info
    return {
      ...mockSafetyInfo,
      country,
    };
  }
}

// Export a singleton instance
export const apiClient = new APIClient();
